"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { ImagePlus, ShieldCheck } from "lucide-react";

function Upload({ id, label, file, setFile }) {
  return <label htmlFor={id} className="group flex min-h-40 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-[#A48E68]/35 bg-[#f8faf8] p-5 text-center transition hover:border-[#006455] hover:bg-emerald-50/30 focus-within:ring-2 focus-within:ring-[#A48E68]"><ImagePlus className="mb-3 text-[#006455]" aria-hidden="true" /><span className="font-black text-[#002723]">{label}</span><span className="mt-1 text-xs text-slate-500">{file ? file.name : "JPEG / PNG / WebP — 5MB"}</span><input id={id} type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={(e) => setFile(e.target.files?.[0] || null)} aria-describedby={`${id}-hint`} /><span id={`${id}-hint`} className="sr-only">اختر صورة واضحة لا تتجاوز خمسة ميغابايت</span></label>;
}

export default function CitizenIdentityForm({ locale = "ar", status = "UNSUBMITTED" }) {
  const isAr = locale === "ar"; const router = useRouter(); const [front, setFront] = useState(null); const [back, setBack] = useState(null); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  async function submit(event) { event.preventDefault(); if (!front || !back) { setNotice(isAr ? "اختر صورتي الوجه الأمامي والخلفي." : "Select both front and back images."); return; } setBusy(true); setNotice(""); const body = new FormData(); body.append("front", front); body.append("back", back); const response = await fetch("/api/citizen/identity/submit", { method: "POST", body }); const data = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { setNotice(data.error || (isAr ? "تعذر رفع الصور." : "Upload failed.")); return; } setNotice(isAr ? "تم استلام الصور وأصبحت الهوية قيد المراجعة." : "Images received. Your identity is now under review."); router.refresh(); }
  if (status === "PENDING" || status === "VERIFIED") return <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6 text-emerald-900"><ShieldCheck className="mb-3" /><h3 className="font-black">{status === "VERIFIED" ? (isAr ? "الهوية موثقة" : "Identity verified") : (isAr ? "الهوية قيد المراجعة" : "Identity under review")}</h3><p className="mt-2 text-sm leading-6">{status === "VERIFIED" ? (isAr ? "يمكنك الآن حجز المقاعد في الفعاليات المتاحة." : "You can now book available cultural events.") : (isAr ? "لا حاجة لإعادة الرفع. سنرسل القرار إلى بريدك." : "No need to upload again. We will email the decision.")}</p></div>;
  return <form onSubmit={submit} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Upload id="identity-front" label={isAr ? "الوجه الأمامي" : "Front side"} file={front} setFile={setFront} /><Upload id="identity-back" label={isAr ? "الوجه الخلفي" : "Back side"} file={back} setFile={setBack} /></div><p className="text-xs leading-6 text-slate-500">{isAr ? "تُحفظ الصور في تخزين خاص ولا تظهر للعامة، ويصل إليها موظفو المراجعة المخولون فقط." : "Images are kept in private storage and are only available to authorized reviewers."}</p><div aria-live="polite" className="min-h-6 text-sm text-amber-800">{notice}</div><button disabled={busy} className="min-h-11 rounded-xl bg-[#003D33] px-6 font-black text-white transition hover:bg-[#002b24] disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#A48E68] focus-visible:ring-offset-2">{busy ? (isAr ? "جاري الرفع..." : "Uploading...") : (isAr ? "إرسال الهوية للمراجعة" : "Submit identity for review")}</button></form>;
}
