import EventBookingPanel from "@/components/citizen/EventBookingPanel";
import { getCurrentCitizenOptional } from "@/lib/citizen-dal";
import { prisma } from "@/lib/prisma";
import { CalendarDays, MapPin } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";

export const dynamic = "force-dynamic";
function formatDate(value, locale) { return new Intl.DateTimeFormat(locale === "ar" ? "ar-SY" : "en-GB", { dateStyle: "full", timeStyle: "short" }).format(value); }
export default async function PublicEventPage({ params }) { const { locale, id } = await params; const [event, optional] = await Promise.all([prisma.event.findFirst({ where: { id, reviewStatus: "APPROVED" }, select: { id: true, titleAr: true, titleEn: true, descriptionAr: true, descriptionEn: true, featuredImage: true, startDate: true, endDate: true, location: true, locationEn: true, governorate: true, governorateEn: true, status: true } }), getCurrentCitizenOptional()]); if (!event) notFound(); let citizen = null; if (optional?.citizenId) { const row = await prisma.citizen.findUnique({ where: { id: optional.citizenId }, select: { emailVerifiedAt: true, identityStatus: true } }); if (row) citizen = { emailVerified: Boolean(row.emailVerifiedAt), identityStatus: row.identityStatus }; } const isAr = locale === "ar"; const title = isAr ? event.titleAr : (event.titleEn || event.titleAr); const description = isAr ? event.descriptionAr : (event.descriptionEn || event.descriptionAr); return <div className="min-h-screen bg-[#f7f8f5] pt-[100px] lg:pt-[122px]" dir={isAr ? "rtl" : "ltr"}><main className="mx-auto w-full max-w-6xl px-4 py-8 sm:px-6 lg:py-12"><Link href={`/${locale}/calendar`} className="inline-flex min-h-11 items-center text-sm font-bold text-[#006455] focus-visible:ring-2 focus-visible:ring-[#A48E68]">{isAr ? "العودة إلى الروزنامة" : "Back to calendar"}</Link><div className="mt-4 overflow-hidden rounded-[2rem] border border-[#A48E68]/20 bg-white shadow-xl"><div className="relative aspect-[16/7] min-h-64 bg-[#003D33]">{event.featuredImage && <Image src={event.featuredImage} alt={title} fill priority sizes="(max-width: 1200px) 100vw, 1152px" className="object-cover" />}<div className="absolute inset-0 bg-gradient-to-t from-[#002723]/95 via-[#002723]/35 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-6 text-white sm:p-10"><p className="text-xs font-black tracking-[0.2em] text-[#d7c49c]">{isAr ? "فعالية ثقافية" : "Cultural event"}</p><h1 className="mt-3 max-w-4xl text-3xl font-black leading-tight sm:text-5xl">{title}</h1></div></div><div className="grid gap-8 p-6 sm:p-10 lg:grid-cols-[1fr_350px]"><article><div className="grid gap-3 border-b border-slate-100 pb-6 sm:grid-cols-2"><p className="flex items-start gap-3 text-sm text-slate-700"><CalendarDays className="shrink-0 text-[#006455]" />{formatDate(event.startDate, locale)}</p><p className="flex items-start gap-3 text-sm text-slate-700"><MapPin className="shrink-0 text-[#006455]" />{isAr ? event.location : (event.locationEn || event.location)}</p></div><h2 className="mt-7 text-xl font-black text-[#002723]">{isAr ? "عن الفعالية" : "About the event"}</h2><div className="html-content mt-4 text-sm leading-8 text-slate-700 sm:text-base" dangerouslySetInnerHTML={{ __html: description || (isAr ? "لا توجد تفاصيل إضافية." : "No additional details.") }} /></article><aside><EventBookingPanel eventId={event.id} locale={locale} citizen={citizen} /></aside></div></div></main></div>; }
