"use client";
import { use, useState } from "react";
import { AlertCircle, Lock } from "lucide-react";
import { useRouter, useSearchParams } from "next/navigation";
import DecorativeCorners from "@/components/DecorativeCorners";

export default function LegalLicensesGatePage(props) {
  const params = use(props.params); const locale = params.locale || "ar"; const isRtl = locale === "ar";
  const router = useRouter(); const searchParams = useSearchParams();
  const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const copy = isRtl ? { title: "بوابة الاختبار الداخلي", desc: "خدمة طلبات التراخيص القانونية قيد الاختبار ولم تُطلق للعامة بعد. أدخل كلمة المرور المؤقتة للمتابعة.", label: "كلمة المرور", button: "دخول", error: "كلمة المرور غير صحيحة" } : { title: "Internal testing gate", desc: "The Legal License Applications service is in internal testing and is not public yet. Enter the temporary password to continue.", label: "Password", button: "Enter", error: "Incorrect password" };
  async function submit(event) { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch("/api/services-gate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password }) }); if (!response.ok) throw new Error(copy.error); const next = searchParams.get("next") || `/${locale}/services/legal-licenses`; router.push(`${next}${window.location.hash || ""}`); } catch (e) { setError(e.message); } finally { setLoading(false); } }
  return <div className="flex min-h-screen items-center justify-center bg-[#F8F3EC] px-4 pt-24" dir={isRtl ? "rtl" : "ltr"}><section className="relative w-full max-w-md rounded-3xl border border-slate-100 bg-white p-8 shadow-sm"><DecorativeCorners /><div className="mb-5 flex h-14 w-14 items-center justify-center rounded-2xl bg-[#054239]/10 text-[#054239]"><Lock className="h-6 w-6" /></div><h1 className="font-qomra text-2xl font-black text-[#054239]">{copy.title}</h1><p className="mt-2 text-sm leading-7 text-slate-500">{copy.desc}</p><form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm font-bold text-slate-700">{copy.label}<input autoFocus type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-[#b9a779] focus:ring-4 focus:ring-[#b9a779]/15" /></label>{error && <p className="flex items-center gap-2 text-xs font-bold text-rose-600"><AlertCircle className="h-4 w-4" />{error}</p>}<button disabled={loading || !password} className="w-full rounded-xl border border-[#b9a779] bg-[#054239] py-3 text-sm font-black text-[#b9a779] disabled:opacity-50">{loading ? "…" : copy.button}</button></form></section></div>;
}
