"use client";
import { useState } from "react";
import { FileText, Printer, Upload } from "lucide-react";
import { useRouter } from "next/navigation";
import { canTransitionLegalLicense, LEGAL_LICENSE_STATUSES, LEGAL_LICENSE_TYPES } from "@/lib/legal-license.mjs";

const STATUS = { DRAFT: "مسودة", SUBMITTED: "مرسل", UNDER_REVIEW: "قيد التدقيق", COMMITTEE_REVIEW: "لدى اللجنة", SUSPENDED: "معلّق للنواقص", LEGAL_APPROVAL: "الاعتماد القانوني", MINISTER_APPROVAL: "اعتماد المفوض", APPROVED: "مقبول", REJECTED: "مرفوض", LICENSE_ISSUED: "صدر الترخيص", COMPLETED: "مكتمل" };
export default function LegalLicenseDetail({ initial, userRole }) {
  const router = useRouter(); const [application, setApplication] = useState(initial); const [nextStatus, setNextStatus] = useState(""); const [note, setNote] = useState(""); const [publicNote, setPublicNote] = useState(""); const [licenseNumber, setLicenseNumber] = useState(initial.licenseNumber || ""); const [licenseDate, setLicenseDate] = useState(initial.licenseDate ? String(initial.licenseDate).slice(0, 10) : ""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const allowed = LEGAL_LICENSE_STATUSES.filter((status) => canTransitionLegalLicense(userRole, application.status, status));
  async function transition() { setBusy(true); setError(""); const res = await fetch(`/api/admin/legal-licenses/${application.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ nextStatus, expectedUpdatedAt: application.updatedAt, note, publicNote, licenseNumber, licenseDate }) }); const data = await res.json(); setBusy(false); if (!res.ok) return setError(data.error || "تعذر حفظ الإجراء"); setApplication(data.application); setNextStatus(""); setNote(""); setPublicNote(""); router.refresh(); }
  async function uploadLicense(file) { if (!file) return; setBusy(true); const form = new FormData(); form.set("file", file); const res = await fetch(`/api/admin/legal-licenses/${application.id}/attachments`, { method: "POST", body: form }); const data = await res.json(); setBusy(false); if (!res.ok) return setError(data.error || "تعذر رفع النسخة"); setApplication((current) => ({ ...current, attachments: [data.attachment, ...(current.attachments || [])] })); }
  return <div className="space-y-6 pb-20" dir="rtl"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-sm font-black text-[#b9a779]" dir="ltr">{application.referenceNo}</p><h1 className="mt-1 text-2xl font-black text-[#054239]">{application.entityName || "طلب ترخيص قانوني"}</h1><p className="mt-1 text-sm text-slate-500">{LEGAL_LICENSE_TYPES[application.licenseType]?.label.ar}</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-[#054239]/10 px-4 py-2 text-xs font-black text-[#054239]">{STATUS[application.status]}</span><button onClick={() => window.print()} className="print:hidden rounded-xl border border-slate-200 p-2.5 text-slate-600"><Printer className="h-4 w-4" /></button></div></header>{error && <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-700">{error}</div>}
    <div className="grid gap-6 xl:grid-cols-[1fr_360px]"><div className="space-y-6"><Section title="بيانات مقدم الطلب"><Grid data={[["الاسم", application.applicantName], ["الرقم الوطني", application.nationalId], ["الهاتف", application.phone], ["البريد", application.email], ["الصفة", application.capacity], ["المحافظة", application.governorate], ["العنوان", application.address]]} /></Section><Section title="بيانات الجهة"><Grid data={[["اسم الجهة", application.entityName], ["الغاية", application.purpose], ["الأهداف", application.objectives], ["النشاط", application.activityDescription]]} /></Section><Section title={`المؤسسون (${application.founders.length})`}><div className="space-y-3">{application.founders.map((founder) => <div key={founder.id} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between"><strong className="text-[#054239]">{founder.fullName}</strong>{founder.isAuthorizedRepresentative && <span className="rounded-full bg-amber-50 px-2 py-1 text-[10px] font-bold text-amber-700">المفوض</span>}</div><Grid data={[["الرقم الوطني", founder.nationalId], ["المهنة", founder.occupation], ["المؤهل", founder.qualification], ["الهاتف", founder.phone], ["البريد", founder.email]]} /></div>)}</div></Section><Section title={`المرفقات (${application.attachments.length})`}><div className="grid gap-2 sm:grid-cols-2">{application.attachments.map((attachment) => <a key={attachment.id} href={`/api/legal-licenses/${application.id}/attachments/${attachment.id}`} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-xs font-bold text-[#054239]"><FileText className="h-4 w-4" /><span className="min-w-0 truncate">{attachment.originalName}</span><span className="mr-auto text-[10px] text-slate-400">v{attachment.version}</span></a>)}</div>{["APPROVED", "LICENSE_ISSUED"].includes(application.status) && <label className="print:hidden mt-4 flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-[#b9a779] p-3 text-sm font-bold text-[#054239]"><Upload className="h-4 w-4" />رفع النسخة الموقعة والمختومة<input type="file" className="hidden" accept=".pdf,image/jpeg,image/png,image/webp" onChange={(e) => uploadLicense(e.target.files?.[0])} /></label>}</Section><Section title="التسلسل الزمني"><ol className="space-y-4">{application.history.map((entry) => <li key={entry.id} className="relative border-r-2 border-[#b9a779]/40 pr-5"><span className="absolute -right-[7px] top-1 h-3 w-3 rounded-full bg-[#b9a779]" /><strong className="text-sm text-slate-700">{STATUS[entry.toStatus] || entry.action}</strong><p className="text-xs text-slate-500">{entry.publicNote || entry.note}</p><time className="text-[10px] text-slate-400">{new Date(entry.createdAt).toLocaleString("ar-SY")}</time></li>)}</ol></Section></div>
      <aside className="print:hidden h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm xl:sticky xl:top-24"><h2 className="font-black text-[#054239]">الإجراء التالي</h2>{allowed.length ? <div className="mt-4 space-y-4"><label className="block text-xs font-bold text-slate-600">الانتقال إلى<select value={nextStatus} onChange={(e) => setNextStatus(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm"><option value="">اختر الإجراء</option>{allowed.map((status) => <option key={status} value={status}>{STATUS[status]}</option>)}</select></label>{["SUSPENDED", "REJECTED"].includes(nextStatus) && <textarea value={publicNote} onChange={(e) => setPublicNote(e.target.value)} placeholder="الملاحظة الظاهرة للمواطن (إلزامية)" className="h-28 w-full rounded-xl border border-slate-200 p-3 text-sm" />}{nextStatus && !["SUSPENDED", "REJECTED"].includes(nextStatus) && <textarea value={note} onChange={(e) => setNote(e.target.value)} placeholder="التوصية أو الملاحظة الداخلية" className="h-28 w-full rounded-xl border border-slate-200 p-3 text-sm" />}{nextStatus === "LICENSE_ISSUED" && <div className="grid gap-3"><input value={licenseNumber} onChange={(e) => setLicenseNumber(e.target.value)} placeholder="رقم الترخيص" className="rounded-xl border border-slate-200 p-3 text-sm" /><input type="date" value={licenseDate} onChange={(e) => setLicenseDate(e.target.value)} className="rounded-xl border border-slate-200 p-3 text-sm" /></div>}<button disabled={!nextStatus || busy} onClick={transition} className="w-full rounded-xl bg-[#054239] py-3 text-sm font-black text-[#b9a779] disabled:opacity-50">{busy ? "…" : "تسجيل الإجراء"}</button></div> : <p className="mt-4 rounded-xl bg-slate-50 p-4 text-sm text-slate-500">لا يوجد انتقال متاح لدورك في هذه المرحلة.</p>}</aside></div></div>;
}
function Section({ title, children }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 border-b border-slate-100 pb-3 text-lg font-black text-[#054239]">{title}</h2>{children}</section>; }
function Grid({ data }) { return <dl className="mt-3 grid gap-3 sm:grid-cols-2">{data.map(([label, value]) => <div key={label}><dt className="text-[11px] font-bold text-slate-400">{label}</dt><dd className="mt-1 whitespace-pre-wrap text-sm font-semibold text-slate-700">{value || "—"}</dd></div>)}</dl>; }
