"use client";
import { useMemo, useState } from "react";
import { Printer, Search } from "lucide-react";
import { useRouter } from "next/navigation";
import { LEGAL_LICENSE_TYPES } from "@/lib/legal-license.mjs";

const STATUS = { DRAFT: "مسودة", SUBMITTED: "مرسل", UNDER_REVIEW: "قيد التدقيق", COMMITTEE_REVIEW: "لدى اللجنة", SUSPENDED: "نواقص", LEGAL_APPROVAL: "اعتماد قانوني", MINISTER_APPROVAL: "اعتماد المفوض", APPROVED: "مقبول", REJECTED: "مرفوض", LICENSE_ISSUED: "صدر الترخيص", COMPLETED: "مكتمل" };
export default function LegalLicenseTable({ items }) {
  const router = useRouter(); const [q, setQ] = useState(""); const [status, setStatus] = useState("ALL"); const [type, setType] = useState("ALL");
  const filtered = useMemo(() => items.filter((item) => { const term = q.trim().toLowerCase(); return (!term || [item.referenceNo, item.applicantName, item.entityName, item.nationalId].some((value) => String(value || "").toLowerCase().includes(term))) && (status === "ALL" || item.status === status) && (type === "ALL" || item.licenseType === type); }), [items, q, status, type]);
  return <div className="space-y-4"><div className="print:hidden grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 md:grid-cols-[1fr_220px_240px_auto]"><label className="relative"><Search className="absolute right-3 top-3 h-4 w-4 text-slate-400" /><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="بحث بالرقم أو الاسم أو الجهة" className="w-full rounded-xl border border-slate-200 py-2.5 pr-10 pl-3 text-sm outline-none focus:border-[#b9a779]" /></label><select value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-xl border border-slate-200 px-3 text-sm"><option value="ALL">كل الحالات</option>{Object.entries(STATUS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><select value={type} onChange={(e) => setType(e.target.value)} className="rounded-xl border border-slate-200 px-3 text-sm"><option value="ALL">كل أنواع التراخيص</option>{Object.values(LEGAL_LICENSE_TYPES).map((item) => <option key={item.value} value={item.value}>{item.label.ar}</option>)}</select><button onClick={() => window.print()} className="flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 text-sm font-bold text-[#054239]"><Printer className="h-4 w-4" />طباعة</button></div>
    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><table className="w-full text-right text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-3">الرقم</th><th className="p-3">مقدم الطلب</th><th className="p-3">الجهة</th><th className="hidden p-3 lg:table-cell">النوع</th><th className="p-3">الحالة</th><th className="hidden p-3 md:table-cell">آخر تحديث</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((item) => <tr key={item.id} onClick={() => router.push(`/admin/legal-licenses/${item.id}`)} className="cursor-pointer hover:bg-slate-50"><td className="p-3 font-mono text-xs font-black text-[#054239]" dir="ltr">{item.referenceNo || "—"}</td><td className="p-3 font-bold text-slate-700">{item.applicantName || "—"}</td><td className="p-3 text-slate-600">{item.entityName || "—"}</td><td className="hidden p-3 text-xs text-slate-500 lg:table-cell">{LEGAL_LICENSE_TYPES[item.licenseType]?.label.ar || "—"}</td><td className="p-3"><span className="rounded-full bg-[#054239]/8 px-2.5 py-1 text-[11px] font-bold text-[#054239]">{STATUS[item.status] || item.status}</span></td><td className="hidden p-3 text-xs text-slate-400 md:table-cell">{new Date(item.updatedAt).toLocaleDateString("en-GB")}</td></tr>)}</tbody></table>{!filtered.length && <div className="p-12 text-center text-sm text-slate-400">لا توجد طلبات مطابقة</div>}</div><p className="text-xs text-slate-400">{filtered.length} طلب</p></div>;
}
