import { NextResponse } from "next/server";
import { generateCompletedLegalLicenseBylawsDocx } from "@/lib/legal-license-bylaws-docx.mjs";
import { canStaffAccessLegalLicenses, findCitizenLegalLicense, legalLicenseTokenFromRequest } from "@/lib/legal-license-server";
import { findDevLegalLicense, legalLicenseDevStoreEnabled } from "@/lib/legal-license-dev-store.mjs";
import { prisma } from "@/lib/prisma";

export async function GET(request, { params }) {
  const { id } = await params;
  const devStore = legalLicenseDevStoreEnabled();
  let application = devStore
    ? findDevLegalLicense(legalLicenseTokenFromRequest(request), { id })
    : await findCitizenLegalLicense(request, { id });

  if (!application && !devStore) {
    const staff = await canStaffAccessLegalLicenses();
    if (staff) {
      application = await prisma.legalLicenseApplication.findUnique({
        where: { id },
        include: { founders: true },
      });
    }
  }

  if (!application) return NextResponse.json({ error: "Application not found" }, { status: 404 });

  try {
    const docx = await generateCompletedLegalLicenseBylawsDocx(application);
    return new NextResponse(docx, {
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "Content-Disposition": `attachment; filename="${application.referenceNo || "legal-license"}-bylaws.docx"`,
        "Cache-Control": "private, no-store",
        "X-Content-Type-Options": "nosniff",
      },
    });
  } catch (error) {
    console.error("Legal-license generated bylaws download failed:", error);
    return NextResponse.json({ error: "Bylaws generation is temporarily unavailable" }, { status: 503 });
  }
}
