import AdminShell from "@/components/admin/AdminShell";
import { getCurrentUser } from "@/lib/dal";
import { can } from "@/lib/permissions";
import { prisma } from "@/lib/prisma";
import { CalendarDays, TicketCheck } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";

export const dynamic = "force-dynamic";
export default async function AdminBookingsPage() { const user = await getCurrentUser(); if (!can(user.role, "VIEW_EVENT_BOOKINGS")) redirect("/admin/dashboard"); const where = user.role === "DIRECTORATE" ? { createdById: user.id } : undefined; const events = await prisma.event.findMany({ where, select: { id: true, titleAr: true, startDate: true, status: true, bookingAvailability: true, capacity: true, bookedCount: true, _count: { select: { bookings: true } } }, orderBy: { startDate: "desc" }, take: 100 }); return <AdminShell user={user}><div className="space-y-6" dir="rtl"><header><p className="text-xs font-black tracking-[0.18em] text-[#A48E68]">إدارة المقاعد</p><h1 className="mt-2 text-2xl font-black text-slate-900">لوحة الحجوزات</h1><p className="mt-1 text-sm text-slate-500">اختر فعالية لضبط السعة ومراجعة الحضور.</p></header><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{events.map((event) => <Link key={event.id} href={`/admin/events/${event.id}/bookings`} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-[#A48E68] hover:shadow-md"><div className="flex items-start justify-between gap-4"><CalendarDays className="text-[#006455]" /><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-600">{event.bookingAvailability}</span></div><h2 className="mt-4 font-black text-slate-900 group-hover:text-[#006455]">{event.titleAr}</h2><p className="mt-2 text-sm text-slate-500">{new Intl.DateTimeFormat("ar-SY", { dateStyle: "medium" }).format(event.startDate)}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4 text-sm"><span className="flex items-center gap-2 font-bold text-slate-700"><TicketCheck size={17} />{event._count.bookings} سجل</span><span className="font-black text-[#003D33]">{event.bookedCount}/{event.capacity || "—"}</span></div></Link>)}</div></div></AdminShell>; }
